import './style.css'

const defaults = { question: 'Ben bir eşşeğim, beni affeder misin?', yesLabel: 'Affettim', noLabel: 'Hayır', successMessage: 'Çok teşekkür ederim. Bu dağ ayısı çok mutlu oldu!', foreverMessage: 'Beni bir kez affettin, bir daha affetmen gereken bir durum yaratmayacağım. 💙💙', noMessages: ['Emin misin?', 'Bir daha denesen?', 'Ama tatlısın?', 'Ama üzülüyorum?', 'Çay içsen?', 'Aa ama yapma?'] }
const app = document.querySelector('#app')
const sessionId = localStorage.getItem('affetbeni-session') || crypto.randomUUID()
localStorage.setItem('affetbeni-session', sessionId)

const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[character])
const getSettings = async () => { try { return { ...defaults, ...(await (await fetch('/api/settings')).json()) } } catch { return defaults } }
const logAction = (action, noCount) => fetch('/api/actions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, noCount, sessionId }) }).catch(() => {})
const flowerMarkup = () => '<div class="flower" aria-hidden="true"><span class="petal p1"></span><span class="petal p2"></span><span class="petal p3"></span><span class="petal p4"></span><span class="petal p5"></span><span class="flower-center"></span><span class="stem"></span><span class="leaf l1"></span><span class="leaf l2"></span></div>'

async function renderHome() {
  const settings = await getSettings()
  const forgiven = localStorage.getItem('affetbeni-forgiven') === 'true'
  let noCount = Number(localStorage.getItem('affetbeni-no-count') || 0)
  let noIndex = Number(localStorage.getItem('affetbeni-no-index') || 0)
  if (forgiven) { const photo = settings.photoUrl ? `<img class="forgiven-photo" src="${escapeHtml(settings.photoUrl)}" alt="Bizi anlatan fotoğraf">` : ''; const note = localStorage.getItem('affetbeni-note') || ''; app.innerHTML = `<main class="afterglow"><div class="afterglow-card">${photo}${flowerMarkup()}<p class="eyebrow">Söz veriyorum</p><h1>${escapeHtml(settings.foreverMessage)}</h1>${note ? `<div class="saved-note"><span>Senin notun</span><p>${escapeHtml(note)}</p></div>` : ''}</div></main>`; return }
  app.innerHTML = `<main class="scene"><div class="spark spark-one"></div><div class="spark spark-two"></div><section class="card" aria-live="polite"><div class="badge">♡ küçük bir ricam var</div><div class="bear" aria-hidden="true">🐻</div><p class="eyebrow">Bana bir şans daha?</p><h1>${escapeHtml(settings.question)}</h1><p id="plea" class="plea">${escapeHtml(settings.noMessages[Math.max(0, noIndex - 1)] || 'Kalbim burada bekliyor...')}</p><div class="actions"><button id="yes" class="yes-button">${escapeHtml(settings.yesLabel)} <span>♡</span></button><button id="no" class="no-button">${escapeHtml(settings.noLabel)}</button></div><div class="counter"><span id="count">${noCount}</span> kez düşündün</div></section></main>`
  const yesButton = document.querySelector('#yes'); const noButton = document.querySelector('#no'); const plea = document.querySelector('#plea'); const count = document.querySelector('#count')
  yesButton.addEventListener('click', async () => { localStorage.setItem('affetbeni-forgiven', 'true'); await logAction('yes', noCount); app.innerHTML = `<main class="success"><div class="success-card"><div class="confetti">✦　✿　✦</div><div class="bear happy" aria-hidden="true">🐻</div><p class="eyebrow">Kalbime güneş doğdu</p><h1>${escapeHtml(settings.successMessage)}</h1><div class="heart-line">♡ ♡ ♡</div><form id="note-form" class="note-form"><label for="note">Bana bir not bırak</label><textarea id="note" rows="3" maxlength="240" placeholder="İçinden ne geçiyorsa..."></textarea><button type="submit">Notu bırak</button></form></div></main>`; document.querySelector('#note-form').addEventListener('submit', (event) => { event.preventDefault(); const note = document.querySelector('#note').value.trim(); if (!note) return; localStorage.setItem('affetbeni-note', note); document.querySelector('.note-form').innerHTML = '<p class="note-saved">Notun kalbime bırakıldı. ♡</p>' }) })
  noButton.addEventListener('click', async () => { noCount += 1; noIndex += 1; localStorage.setItem('affetbeni-no-count', noCount); localStorage.setItem('affetbeni-no-index', noIndex); count.textContent = noCount; plea.textContent = settings.noMessages[(noIndex - 1) % settings.noMessages.length]; yesButton.style.setProperty('--yes-scale', Math.min(1.75, 1 + noCount * 0.12)); noButton.style.setProperty('--no-scale', Math.max(0.52, 1 - noCount * 0.1)); if (noCount >= 7) noButton.textContent = 'Hayır...'; await logAction('no', noCount) })
}

const activityMarkup = (actions) => actions.length ? actions.map((item) => `<article class="activity ${item.action === 'yes' ? 'is-yes' : 'is-no'}"><span class="activity-icon">${item.action === 'yes' ? '✓' : '×'}</span><div><strong>${item.action === 'yes' ? 'Affettim' : 'Hayır'}</strong><small>${new Date(item.createdAt).toLocaleString('tr-TR')} · ${item.noCount || 0} hayır · IP: ${escapeHtml(item.ip || 'Eski kayıt / IP yok')}</small></div></article>`).join('') : '<p class="empty-state">Henüz cevap kaydı yok.</p>'

async function renderControl() {
  const settings = await getSettings(); const actions = await fetch('/api/actions').then((response) => response.json()).catch(() => [])
  app.innerHTML = `<main class="control"><header class="control-header"><div><p class="eyebrow">Sadece senin için</p><h1>Affet Beni / Kontrol</h1></div><span class="live-dot">● kayıt açık</span></header><section class="control-grid"><form id="settings-form" class="panel settings-panel"><div class="panel-heading"><div><p class="eyebrow">Metin stüdyosu</p><h2>Mesajlarını düzenle</h2></div><button class="save-button" type="submit">Kaydet</button></div><label>Ana soru<input name="question" value="${escapeHtml(settings.question)}"></label><div class="two-col"><label>Affettim butonu<input name="yesLabel" value="${escapeHtml(settings.yesLabel)}"></label><label>Hayır butonu<input name="noLabel" value="${escapeHtml(settings.noLabel)}"></label></div><label>Affedince görünecek yazı<textarea name="successMessage" rows="2">${escapeHtml(settings.successMessage)}</textarea></label><label>Bir sonraki ziyaret yazısı<textarea name="foreverMessage" rows="2">${escapeHtml(settings.foreverMessage)}</textarea></label><label>Son ziyaret fotoğrafı URL'si <span class="hint">Boş bırakırsan çiçek görünür</span><input name="photoUrl" type="url" placeholder="https://..." value="${escapeHtml(settings.photoUrl || '')}"></label><label>Hayır mesajları <span class="hint">Her satıra bir mesaj</span><textarea name="noMessages" rows="6">${escapeHtml(settings.noMessages.join('\n'))}</textarea></label><p id="save-status" class="save-status"></p></form><section class="panel activity-panel"><div class="panel-heading"><div><p class="eyebrow">Canlı kayıt</p><h2>Son cevaplar</h2></div><div class="activity-tools"><span class="total-count">${actions.length} kayıt</span><button id="reset-actions" class="reset-button" type="button">Logları temizle</button></div></div><div id="activity-list">${activityMarkup(actions)}</div></section></section></main>`
  document.querySelector('#settings-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const updated = { question: form.get('question'), yesLabel: form.get('yesLabel'), noLabel: form.get('noLabel'), successMessage: form.get('successMessage'), foreverMessage: form.get('foreverMessage'), photoUrl: form.get('photoUrl'), noMessages: form.get('noMessages').split('\n').map((line) => line.trim()).filter(Boolean) }; await fetch('/api/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(updated) }); document.querySelector('#save-status').textContent = 'Ayarlar kaydedildi.' })
  document.querySelector('#reset-actions').addEventListener('click', async () => { if (!window.confirm('Tüm cevap logları silinsin mi?')) return; await fetch('/api/actions', { method: 'DELETE' }); document.querySelector('#activity-list').innerHTML = activityMarkup([]); document.querySelector('.total-count').textContent = '0 kayıt' })
}

window.location.pathname === '/kontrol' ? renderControl() : renderHome()
